- defaults:
    link:
      create: true
      relink: true

- clean: ['~']

- link:
    ~/.dotfiles: ''
    ~/.zshrc: zshrc
    ~/.vimrc: vimrc
    ~/.RProfile: RProfile
    ~/.bash_profile:
      path: bash_profile
      relink: true
    ~/.dot_helpers:
      glob: true
      path: dot_helpers/*
    ~/.config/helix/config.toml:
      create: true
      path: config/helix/config.toml
    ~/.config/kitty/current-theme.conf:
      create: true
      path: config/kitty/current-theme.conf
    ~/.config/kitty/kitty.conf:
      create: true
      path: config/kitty/kitty.conf


- shell:
  - [git submodule update --init --recursive, Installing submodules]
