#.git_config
# bash
# rprofile
# .R
# vim
# secrets method


- defaults:
    link:
      create: true
      relink: true

- clean: ['~']

- link:
    ~/.dotfiles: ''
    ~/.vimrc: vimrc
    ~/.RProfile: RProfile
    ~/.gitconfig: gitconfig
    ~/.bash_profile: bash_profile
    ~/.dot_helpers:
        glob: true
        path: dot_helpers/*


- shell:
  - [git submodule update --init --recursive, Installing submodules]

# Create secrets file if doesn't exist