- defaults:
    link:
      create: true
      relink: true

- clean: ['~']

- create:
    ~/.claude:

- link:
    ~/.dotfiles: ''
    ~/.zshrc: zshrc
    ~/.vimrc: vimrc
    ~/.RProfile: RProfile
    ~/.bash_profile:
      path: bash_profile
      relink: true
    ~/.dot_helpers:
      glob: true
      path: dot_helpers/*
    ~/.config/helix/config.toml:
      create: true
      path: config/helix/config.toml
    ~/.config/kitty/current-theme.conf:
      create: true
      path: config/kitty/current-theme.conf
    ~/.config/kitty/kitty.conf:
      create: true
      path: config/kitty/kitty.conf
    ~/.claude/CLAUDE.md:
      create: true
      path: claude/agents.md
    ~/AGENTS.md:
      create: true
      path: claude/agents.md
    ~/.kilocode/rules/AGENTS.md:
      create: true
      path: claude/agents.md
    ~/.claude/commands:
      create: true
      glob: true
      path: claude/commands/*
    ~/.claude/agents:
      create: true
      glob: true
      path: claude/subagents/*


- shell:
  - [git submodule update --init --recursive, Installing submodules]
