- defaults:
    link:
      create: true
      relink: true

- clean: ['~']

- link:
    ~/.dotfiles: ''
    ~/.zshrc: zshrc
    ~/.vimrc: vimrc
    ~/.RProfile: RProfile
    ~/.bash_profile:
      path: bash_profile
      relink: true
    ~/.dot_helpers:
      glob: true
      path: dot_helpers/*


- shell:
  - [git submodule update --init --recursive, Installing submodules]
